
controller_manager:
  ros__parameters:
    update_rate: 50

    drum_lift_cont:
      type: velocity_controllers/JointGroupVelocityController
    
    drum_cont:
      type: velocity_controllers/JointGroupVelocityController

    diff_cont:
      type: diff_drive_controller/DiffDriveController 

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    

diff_cont:
  ros__parameters:

    publish_rate: 50.0
    base_frame_id: base_footprint
    publish_tf: false

    left_wheel_names:  ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.33
    wheel_radius: 0.10

    use_stamped_vel: false

    odom_frame_id: odom
    enable_odom_tf: false

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0

drum_lift_cont:
  ros__parameters:
    joints:
      - drum_joint

drum_cont:
  ros__parameters:
    joints:
      - drum_spin_joint